import { useEffect, useMemo, useState } from 'react';
import { demoGateway } from './demoGateway';
import type { ChatSurface, JarvisMode, JarvisSnapshot, ProjectState } from './contracts';
import './functional.css';

type Space = 'HOME' | 'CHAT' | 'PROJECTS' | 'MIND' | 'CAPABILITIES' | 'SELF';
const spaces: Space[] = ['HOME', 'CHAT', 'PROJECTS', 'MIND', 'CAPABILITIES', 'SELF'];
const modeLabels: Record<JarvisMode, string> = { Thinking: 'COGNITIVE LOOP', Learning: 'LEARNING', Working: 'WORKING', Monitoring: 'MONITORING', Waiting: 'STANDING BY', 'Needs You': 'ATTENTION REQUIRED' };
const chatLabels: Record<ChatSurface, string> = { CONVERSATION: 'Conversation', WORKSPACE: 'Workspace', RESEARCH: 'Research', PLANNING: 'Planning' };\nconst spaceLabels: Record<Space, string> = { HOME: 'HOME', CHAT: 'CHAT', PROJECTS: 'WORK', MIND: 'MIND', CAPABILITIES: 'CAPABILITIES', SELF: 'SELF' };
const iconPaths: Record<string, string> = { HOME: 'M3 11 12 4l9 7M5 10v10h14V10M9 20v-6h6v6', CHAT: 'M4 5h16v11H8l-4 4V5', PROJECTS: 'M4 6h16v13H4zM4 10h16M8 6V4h8v2', MIND: 'M12 4v16M4 12h16M7 7l10 10M17 7 7 17', CAPABILITIES: 'M12 3l2.1 5.2L20 10l-5.9 1.8L12 17l-2.1-5.2L4 10l5.9-1.8L12 3z', SELF: 'M12 4a8 8 0 1 0 8 8 8 8 0 0 0-8-8zm0 3v5l3 2', MENU: 'M4 7h16M4 12h16M4 17h16' };

function Icon({ name }: { name: string }) { return <svg className="nav-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={iconPaths[name] ?? iconPaths.MENU} /></svg>; }

function App() {
  const [space, setSpace] = useState<Space>('HOME');
  const [collapsed, setCollapsed] = useState(false);
  const [snapshot, setSnapshot] = useState<JarvisSnapshot>(() => demoGateway.snapshotSync());
  const [composer, setComposer] = useState('');
  const [chatSurface, setChatSurface] = useState<ChatSurface>('CONVERSATION');
  const [selectedWorkspaceId, setSelectedWorkspaceId] = useState('jarvis');
  const [selectedProjectId, setSelectedProjectId] = useState('jarvis-interface');
  const [chatHistory, setChatHistory] = useState<Record<ChatSurface, string[]>>({ CONVERSATION: [], WORKSPACE: [], RESEARCH: [], PLANNING: [] });
  const [lastEvent, setLastEvent] = useState('Ready');

  useEffect(() => demoGateway.subscribe('desktop', (event) => { setLastEvent(event.detail ? `${event.title} · ${event.detail}` : event.title); setSnapshot(demoGateway.snapshotSync()); }), []);
  const current = useMemo(() => ({ ...snapshot, modeLabel: modeLabels[snapshot.mode] }), [snapshot]);

  const submit = async () => {
    const value = composer.trim();
    if (!value) return;
    setChatHistory((history) => ({ ...history, [chatSurface]: [...history[chatSurface], value] }));
    setComposer(''); setSpace('CHAT');
    const event = await demoGateway.submit({ text: value, sessionId: 'desktop', surface: chatSurface });
    setLastEvent(event.title); setSnapshot(demoGateway.snapshotSync());
  };

  const controlProject = async (projectId: string, next: Extract<ProjectState, 'ACTIVE' | 'PAUSED'>) => {
    const event = await demoGateway.submit({ text: `${next === 'PAUSED' ? 'Pause' : 'Resume'} project ${projectId}`, sessionId: 'desktop', surface: 'PROJECTS', projectId });
    setLastEvent(event.title); setSnapshot(demoGateway.snapshotSync());
  };

  const selectWorkspaceDirectory = async () => {
    const picker = (window as Window & { showDirectoryPicker?: () => Promise<{ name: string }> }).showDirectoryPicker;
    if (!picker) return;
    const directory = await picker();
    const event = await demoGateway.submit({ text: `Select workspace directory ${directory.name}`, sessionId: 'desktop', surface: 'WORKSPACE' });
    const next = demoGateway.snapshotSync();
    const selected = next.workspaces.find((workspace) => workspace.name === directory.name);
    if (selected) setSelectedWorkspaceId(selected.id);
    setLastEvent(event.title); setSnapshot(next);
  };

  return <div className={`shell mode-${snapshot.mode.toLowerCase().replace(/\s+/g, '-')} ${collapsed ? 'nav-collapsed' : ''}`}>
    <div className="ambient ambient-a" /><div className="ambient ambient-b" /><div className="ambient-core" aria-hidden="true"><span /></div>
    <aside className="sidebar" aria-label="JARVIS navigation">
      <div className="sidebar-brand"><button className="brand" onClick={() => setSpace('HOME')} aria-label="JARVIS Home"><span className="brand-mark">J</span><span className="brand-word">JARVIS</span></button><button className="sidebar-toggle" onClick={() => setCollapsed((value) => !value)} aria-label={collapsed ? 'Expand navigation' : 'Collapse navigation'}><Icon name="MENU" /></button></div>
      <div className="sidebar-status"><span className="pulse" /> <span className="sidebar-status-text">{snapshot.online ? 'ONLINE' : 'OFFLINE'}</span><small>{current.modeLabel}</small></div>
      <nav className="sidebar-nav">{spaces.map((item) => <button key={item} className={item === space ? 'nav-item active' : 'nav-item'} onClick={() => setSpace(item)} title={collapsed ? item : undefined}><Icon name={item} /><span>{spaceLabels[item]}</span></button>)}</nav>
      <div className="sidebar-foot"><span className="sidebar-resource-dot" /><div><b>{snapshot.resources.strategy === 'SEQUENTIAL' ? 'RESOURCE GUARD' : 'LIMITED CONCURRENCY'}</b><small>CPU {snapshot.resources.cpuLoad}% · MEM {snapshot.resources.memoryLoad}%</small></div></div>
    </aside>

    <header className="topbar"><div className="topbar-left"><span className="top-context">{spaceLabels[space]}</span><span className="top-divider" /><span className="top-focus">{snapshot.currentFocus}</span></div><div className="topbar-right"><span className={`pressure pressure-${snapshot.resources.pressure.toLowerCase()}`}>{snapshot.resources.pressure}</span><span className="top-meta">MODELS <strong>{snapshot.models.filter((model) => model.state === 'ACTIVE').length}</strong> · PROJECTS <strong>{snapshot.projects.length}</strong></span></div></header>

    <main className="layout">
      <section className="hero"><div className="hero-eyebrow">JARVIS SYSTEM STATE</div><div className="hero-title">{snapshot.mode}</div><div className="hero-focus">{snapshot.currentFocus}</div><div className="hero-metrics"><Metric label="CAPABILITIES" value={snapshot.activeCapabilities} /><Metric label="SOURCES" value={snapshot.monitoredSources} /><Metric label="PROJECTS" value={snapshot.projects.length} /><Metric label="ATTENTION" value={snapshot.attentionRequired ? 'YES' : 'CLEAR'} /></div><div className="state-pulse"><span className="state-pulse-core" /><div><strong>{snapshot.mode}</strong><small>{lastEvent}</small></div><span className="state-pulse-time">{snapshot.lastStateChange}</span></div></section>
      {space === 'HOME' && <Home snapshot={snapshot} onNavigate={setSpace} />}
      {space === 'CHAT' && <Chat surface={chatSurface} setSurface={setChatSurface} history={chatHistory[chatSurface]} composer={composer} setComposer={setComposer} submit={submit} snapshot={snapshot} selectedWorkspaceId={selectedWorkspaceId} onSelectWorkspace={setSelectedWorkspaceId} onSelectDirectory={selectWorkspaceDirectory} selectedProjectId={selectedProjectId} setSelectedProjectId={setSelectedProjectId} />}
      {space === 'PROJECTS' && <Projects snapshot={snapshot} selectedProjectId={selectedProjectId} setSelectedProjectId={setSelectedProjectId} controlProject={controlProject} onNavigate={setSpace} />}
      {space === 'MIND' && <Mind snapshot={snapshot} />}
      {space === 'CAPABILITIES' && <Capabilities snapshot={snapshot} />}
      {space === 'SELF' && <Self snapshot={snapshot} />}
    </main>
  </div>;
}

function Metric({ label, value }: { label: string; value: string | number }) { return <span>{label} <b>{value}</b></span>; }
function Home({ snapshot, onNavigate }: { snapshot: JarvisSnapshot; onNavigate: (space: Space) => void }) { const active = snapshot.projects.filter((p) => p.state === 'ACTIVE' || p.state === 'PAUSED'); return <section className="home-grid">
  <div className="panel cockpit"><div className="panel-kicker">AWARENESS</div><div className="cockpit-body"><div><span className="signal-label">WHAT MATTERS NOW</span><strong>{snapshot.currentFocus}</strong><p>{snapshot.mode === 'Needs You' ? 'JARVIS is waiting for your presence.' : 'JARVIS is observing current context and maintaining its active systems.'}</p></div><div className="signal-ring"><span>{snapshot.cognitiveActivity}</span><small>COGNITION</small></div></div><div className="cockpit-footer"><span>Last state change</span><b>{snapshot.lastStateChange}</b></div></div>
  <div className={`panel attention ${snapshot.attentionRequired ? 'attention-hot' : ''}`}><div className="panel-kicker">ATTENTION</div><div className="attention-number">{snapshot.attentionRequired ? 'YES' : 'CLEAR'}</div><div className="attention-copy">{snapshot.attentionReason}</div><button className="text-action" onClick={() => onNavigate('PROJECTS')}>Review projects →</button></div>
  <div className="panel intelligence wide"><div className="panel-heading"><span>RECENT INTELLIGENCE</span><small>LIVE</small></div><div className="activity-list">{snapshot.activity.map((item) => <div className="activity-item" key={item.id}><span className="activity-dot" /><div><b>{item.title}</b><p>{item.detail}</p></div><time>{item.timestamp}</time></div>)}</div></div>
  <div className="panel work-overview"><div className="panel-heading"><span>PROJECTS</span><small>{active.length} ACTIVE</small></div>{snapshot.projects.map((project) => <div className="project" key={project.id}><div><b>{project.name}</b><span>{project.state}</span></div>{typeof project.progress === 'number' && <div className="bar"><span style={{ width: `${project.progress}%` }} /></div>}</div>)}<button className="panel-action" onClick={() => onNavigate('PROJECTS')}>Open projects →</button></div>
  <div className="panel capability-overview"><div className="panel-heading"><span>SYSTEM FABRIC</span><small>LIVE</small></div><div className="cap-row"><span className="state-dot ready" /><b>Device</b><span>{snapshot.device.os}</span></div><div className="cap-row"><span className="state-dot connected" /><b>Models</b><span>{snapshot.models.filter((m) => m.state === 'ACTIVE').length} ACTIVE</span></div><div className="cap-row"><span className="state-dot online" /><b>Capabilities</b><span>{snapshot.capabilities.length} KNOWN</span></div><button className="panel-action" onClick={() => onNavigate('CAPABILITIES')}>Open capabilities →</button></div>
  <div className="panel device-overview"><div className="panel-heading"><span>DEVICE</span><small>{snapshot.device.name}</small></div><div className="device-grid">{[['CPU', snapshot.device.cpu], ['MEMORY', snapshot.device.memory], ['GPU', snapshot.device.gpu], ['STORAGE', snapshot.device.storage]].map(([label, value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</div></div>
  <div className="panel model-overview"><div className="panel-heading"><span>MODEL ASSIGNMENTS</span><small>ROLE / STATE</small></div>{snapshot.models.map((model) => <div className="model-row" key={model.id}><div><b>{model.name}</b><span>{model.role}</span></div><strong>{model.state}</strong></div>)}</div>
</section>; }

function Chat({ surface, setSurface, history, composer, setComposer, submit, snapshot, selectedWorkspaceId, onSelectWorkspace, onSelectDirectory, selectedProjectId, setSelectedProjectId }: { surface: ChatSurface; setSurface: (surface: ChatSurface) => void; history: string[]; composer: string; setComposer: (value: string) => void; submit: () => void; snapshot: JarvisSnapshot; selectedWorkspaceId: string; onSelectWorkspace: (id: string) => void; onSelectDirectory: () => Promise<void>; selectedProjectId: string; setSelectedProjectId: (id: string) => void }) {
  const activeWorkspace = snapshot.workspaces.find((w) => w.id === selectedWorkspaceId) ?? snapshot.workspaces[0];
  const activeProject = snapshot.projects.find((p) => p.id === selectedProjectId) ?? snapshot.projects[0];
  const definitions: Record<ChatSurface, { kicker: string; description: string; placeholder: string; tag: string }> = {
    CONVERSATION: { kicker: 'GENERAL INTELLIGENCE', description: 'General conversation with JARVIS. This surface owns its own history.', placeholder: 'Talk to JARVIS...', tag: 'TALK' },
    WORKSPACE: { kicker: 'LITERAL WORKSPACE', description: 'A real directory-rooted environment for inspection, generation, editing, coding and verification.', placeholder: `Command JARVIS in ${activeWorkspace?.name ?? 'this workspace'}...`, tag: 'BUILD' },
    RESEARCH: { kicker: 'ENGINEERING THINK TANK', description: 'Collect topics, gather evidence, brainstorm, challenge ideas and think on research.', placeholder: 'Add a research direction, question, source or thought...', tag: 'THINK' },
    PLANNING: { kicker: 'PLANNING + AUTOMATION', description: 'Create plans for JARVIS to execute or automate, including recurring information gathering and scraping.', placeholder: 'Describe an outcome or automation you want planned...', tag: 'PLAN' },
  };
  const active = definitions[surface];
  const histories = snapshot.chatHistory.filter((entry) => entry.surface === surface);
  return <section className="chat-shell"><aside className="chat-sidebar panel"><div className="panel-kicker">{chatLabels[surface].toUpperCase()}</div><button className="chat-new">+ New {chatLabels[surface].toLowerCase()}</button>{(Object.keys(chatLabels) as ChatSurface[]).map((item) => <button key={item} className={item === surface ? 'chat-mode active' : 'chat-mode'} onClick={() => setSurface(item)}><span>{chatLabels[item]}</span><small>{definitions[item].tag}</small></button>)}
    <div className="chat-toolbox history-box"><span className="panel-kicker">{surface === 'RESEARCH' ? 'RESEARCH HISTORY' : surface === 'CONVERSATION' ? 'CONVERSATION HISTORY' : `${chatLabels[surface].toUpperCase()} HISTORY`}</span>{histories.map((entry) => <button className="history-item" key={entry.id}><b>{entry.title}</b><small>{entry.timestamp}</small><span>{entry.preview}</span></button>)}{history.length === 0 && <div className="history-empty">No local messages in this session.</div>}</div>
    {surface === 'WORKSPACE' && <div className="chat-toolbox"><span className="panel-kicker">WORKSPACE ROOT</span>{snapshot.workspaces.map((workspace) => <button className={`workspace-item ${workspace.id === selectedWorkspaceId ? 'selected' : ''}`} onClick={() => onSelectWorkspace(workspace.id)} key={workspace.id}><b>{workspace.name}</b><small>{workspace.path}</small></button>)}<button className="soft-action" onClick={() => void onSelectDirectory()}>+ Select directory</button><div className="workspace-project-link"><span>ACTIVE PROJECT</span><button onClick={() => setSelectedProjectId(activeProject.id)}>{activeProject.name}</button></div></div>}
    {surface === 'RESEARCH' && <div className="chat-toolbox"><span className="panel-kicker">TOPICS</span>{snapshot.researchTopics.map((topic) => <button className={`research-topic ${topic.state === 'ACTIVE' ? 'selected' : ''}`} key={topic.id}><b>{topic.title}</b><small>{topic.state} · {topic.sourceCount} sources · {topic.thoughtCount} thoughts</small></button>)}</div>}
    {surface === 'PLANNING' && <div className="chat-toolbox"><span className="panel-kicker">PLANS</span>{snapshot.plans.map((plan) => <button className="plan-item" key={plan.id}><b>{plan.title}</b><small>{plan.state}{plan.automation ? ` · ${plan.automation}` : ''}</small></button>)}</div>}
  </aside><section className="panel chat-main"><div className="chat-header"><div><span className="panel-kicker">{active.kicker}</span><h1>{chatLabels[surface]}</h1><p>{active.description}</p></div><span className="chat-status"><i /> LIVE SURFACE</span></div>{surface === 'CONVERSATION' && <div className="chat-history">{history.length === 0 ? <div className="chat-empty"><span className="empty-orb" /><h2>Talk to JARVIS.</h2><p>Conversation has its own history. Other Chat systems are deliberately specialized.</p></div> : history.map((message, index) => <div className="chat-message" key={`${message}-${index}`}><span>YOU</span><p>{message}</p></div>)}</div>}{surface === 'WORKSPACE' && <WorkspaceSurface workspace={activeWorkspace} />}{surface === 'RESEARCH' && <ResearchSurface snapshot={snapshot} />}{surface === 'PLANNING' && <PlanningSurface snapshot={snapshot} />}<div className="chat-composer"><textarea value={composer} onChange={(event) => setComposer(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); submit(); } }} placeholder={active.placeholder} /><button onClick={submit} aria-label="Send command">↑</button></div></section></section>;
}
function ConversationSurface({ chat }: { chat: string[] }) { return <div className="chat-history">{chat.map((message, index) => <div className="chat-message" key={`${message}-${index}`}><span>YOU</span><p>{message}</p></div>)}</div>; }
function WorkspaceSurface({ workspace }: { workspace?: JarvisSnapshot['workspaces'][number] }) { return <div className="special-surface"><div className="workspace-banner"><div><span className="surface-label">WORKSPACE ROOT</span><h2>{workspace?.name ?? 'No workspace selected'}</h2><p>{workspace?.path ?? 'Select a directory to give this workspace a root.'}</p></div><span className="surface-state">{workspace?.status ?? 'AVAILABLE'}</span></div><div className="workspace-grid">{[['INSPECT', 'Understand before changing', 'JARVIS should inspect the selected workspace and establish context first.'], ['GENERATE', 'Build inside the root', 'Code, documents and project scaffolding belong to this workspace.'], ['EDIT', 'Modify existing work', 'Changes stay tied to the chosen workspace and its project context.'], ['VERIFY', 'Prove the result', 'Diffs, tests and resulting state should be visible before continuation.']].map(([label, title, detail]) => <div className="surface-card" key={label}><span>{label}</span><b>{title}</b><p>{detail}</p></div>)}</div></div>; }
function ResearchSurface({ snapshot }: { snapshot: JarvisSnapshot }) { const thoughtOn = snapshot.researchTopics.filter((topic) => topic.state === 'THOUGHT_ON'); return <div className="special-surface"><div className="research-command"><div><span className="surface-label">THINK TANK</span><h2>Think with the material.</h2><p>Research is an engineering workspace: collect, reason, challenge, compare and revisit.</p></div><span className="surface-state">{thoughtOn.length} THOUGHT ON</span></div><div className="research-board">{snapshot.researchTopics.map((topic) => <article className="research-card" key={topic.id}><div className="research-card-top"><span>{topic.state}</span><button>THINK →</button></div><h3>{topic.title}</h3><p>{topic.detail}</p><div className="research-footer"><span>{topic.sourceCount} SOURCES · {topic.thoughtCount} THOUGHTS</span><b>{topic.lastThought ?? 'Waiting for deeper thought.'}</b></div></article>)}</div></div>; }
function PlanningSurface({ snapshot }: { snapshot: JarvisSnapshot }) { return <div className="special-surface"><div className="planning-command"><span className="surface-label">PLANNING + AUTOMATION</span><h2>Prepare JARVIS to execute.</h2><p>Plans can become direct project work or recurring automation such as scraping, monitoring and information gathering.</p></div><div className="plan-board">{snapshot.plans.map((plan) => <article className="plan-card" key={plan.id}><div className="plan-card-top"><span>{plan.state}</span><b>{plan.steps.length} STEPS</b></div><h3>{plan.title}</h3>{plan.automation && <div className="automation-label">AUTOMATION · {plan.automation}</div>}{plan.steps.map((step, index) => <div className={`plan-step ${plan.currentStep === index + 1 ? 'current' : ''}`} key={step}><span>{index + 1}</span>{step}</div>)}</article>)}</div></div>; }
function Projects({ snapshot, selectedProjectId, setSelectedProjectId, controlProject, onNavigate }: { snapshot: JarvisSnapshot; selectedProjectId: string; setSelectedProjectId: (id: string) => void; controlProject: (id: string, state: Extract<ProjectState, 'ACTIVE' | 'PAUSED'>) => Promise<void>; onNavigate: (space: Space) => void }) { const selected = snapshot.projects.find((p) => p.id === selectedProjectId) ?? snapshot.projects[0]; return <section className="space-panel panel"><div className="work-control-head"><div><div className="panel-kicker">PROJECT CONTROL</div><h1>Projects</h1><p className="space-subtitle">Editable JARVIS work objects with progress, context, workspace, plans, feedback, boundaries and runtime control.</p></div><button className="panel-action" onClick={() => onNavigate('CHAT')}>Create through Chat →</button></div><div className="project-control-layout"><aside className="project-list">{snapshot.projects.map((project) => <button key={project.id} className={project.id === selected.id ? 'project-select active' : 'project-select'} onClick={() => setSelectedProjectId(project.id)}><span>{project.state}</span><b>{project.name}</b><small>{project.progress ?? 0}% · {project.currentAction ?? 'No current action'}</small></button>)}</aside><div className="project-detail"><div className="work-runtime"><div><span className="surface-label">PROJECT STATE</span><strong>{selected.state}</strong><p>{selected.detail ?? 'Project context is being maintained.'}</p></div><button className={`control-toggle ${selected.state === 'PAUSED' ? 'paused' : ''}`} disabled={selected.state !== 'ACTIVE' && selected.state !== 'PAUSED'} onClick={() => void controlProject(selected.id, selected.state === 'ACTIVE' ? 'PAUSED' : 'ACTIVE')}><span />{selected.state === 'PAUSED' ? 'RESUME' : 'PAUSE'}</button></div><div className="project-detail-grid"><div className="surface-card"><span>PROGRESS</span><b>{selected.progress ?? 0}%</b>{typeof selected.progress === 'number' && <div className="bar"><span style={{ width: `${selected.progress}%` }} /></div>}<p>{selected.currentAction ?? 'No active operation.'}</p></div><div className="surface-card"><span>WORKSPACE</span><b>{snapshot.workspaces.find((w) => w.id === selected.workspaceId)?.name ?? 'Not assigned'}</b><p>{snapshot.workspaces.find((w) => w.id === selected.workspaceId)?.path ?? 'Select a workspace in Chat.'}</p></div><div className="surface-card"><span>PLANS</span><b>{snapshot.plans.filter((plan) => plan.target === selected.name || plan.target === 'JARVIS UI').length}</b><p>Plans connected to this project.</p></div><div className="surface-card"><span>FEEDBACK</span><b>READY</b><p>Pause before supplying new guidance, commands, guidelines or boundaries.</p></div></div></div></div></section>; }
function Mind({ snapshot }: { snapshot: JarvisSnapshot }) {
  const [view, setView] = useState<'EXPLORER' | 'GRAPH' | 'THINKING'>('EXPLORER');
  const [selectedRoot, setSelectedRoot] = useState('Memory');
  const roots = [
    ['Memory', 'Stored context, facts and durable experience.'],
    ['Thinking', 'Active reasoning, questions and working context.'],
    ['Plans', 'Outcomes, procedures and future actions.'],
    ['Learning', 'Evaluation, adaptation and reliability signals.'],
    ['Relationships', 'People, systems, concepts and their connections.'],
    ['Projects', 'Work objects connected to workspace and plans.'],
    ['Knowledge', 'Organized information and evidence.'],
    ['Experiences', 'What JARVIS has encountered and learned from.'],
    ['Preferences', 'Stable user and system preferences.'],
    ['Goals', 'Longer-horizon objectives and direction.'],
    ['Skills', 'Capabilities JARVIS can develop or invoke.'],
    ['Workflows', 'Repeatable procedures and automation patterns.'],
  ];
  const root = roots.find(([name]) => name === selectedRoot) ?? roots[0];
  return <section className="space-panel panel mind-core-panel">
    <div className="panel-kicker">MIND CORE · INTERNAL WORLD</div>
    <div className="space-heading-row">
      <div><h1>Mind</h1><p className="space-subtitle">The core environment for context, memory, thought, plans, learning and relationships. This is where JARVIS's internal world becomes inspectable.</p></div>
      <div className="segmented"><button className={view === 'EXPLORER' ? 'active' : ''} onClick={() => setView('EXPLORER')}>Explorer</button><button className={view === 'GRAPH' ? 'active' : ''} onClick={() => setView('GRAPH')}>Graph</button><button className={view === 'THINKING' ? 'active' : ''} onClick={() => setView('THINKING')}>Thinking</button></div>
    </div>
    {view === 'EXPLORER' && <div className="mind-explorer-layout"><aside className="mind-root-list">{roots.map(([name, detail]) => <button key={name} className={selectedRoot === name ? 'mind-root active' : 'mind-root'} onClick={() => setSelectedRoot(name)}><span>◈</span><div><b>{name}</b><small>{detail}</small></div></button>)}</aside><div className="mind-root-detail"><div className="mind-context-banner"><span>SELECTED ROOT</span><strong>{root[0]}</strong><p>{root[1]}</p></div><div className="mind-stat-grid"><div><span>ACTIVE FOCUS</span><b>{snapshot.currentFocus}</b></div><div><span>PROJECTS</span><b>{snapshot.projects.length}</b></div><div><span>RESEARCH</span><b>{snapshot.researchTopics.length}</b></div><div><span>PLANS</span><b>{snapshot.plans.length}</b></div></div><div className="surface-card mind-detail-card"><span>ROOT STATE</span><b>{root[0]} is a first-class Mind domain</b><p>This surface is intentionally an explorer rather than a dashboard. Selecting a domain should eventually open its real records, provenance, relationships, history and operations.</p></div></div></div>}
    {view === 'GRAPH' && <div className="relationship-map mind-graph"><span className="node center">MIND CORE</span><span className="node n1">MEMORY</span><span className="node n2">THINKING</span><span className="node n3">PLANS</span><span className="node n4">LEARNING</span><span className="node n5">PROJECTS</span><span className="node n6">RELATIONSHIPS</span>{['c1','c2','c3','c4','c5','c6'].map((item) => <div className={`connection ${item}`} key={item} />)}</div>}
    {view === 'THINKING' && <div className="mind-thinking-grid"><div className="surface-card mind-active-thought"><span>ACTIVE CONTEXT</span><b>{snapshot.currentFocus}</b><p>Current context JARVIS is carrying into its cognitive loop.</p></div>{snapshot.researchTopics.map((topic) => <div className="surface-card" key={topic.id}><span>{topic.state}</span><b>{topic.title}</b><p>{topic.lastThought ?? 'Awaiting deeper thought.'}</p></div>)}</div>}
    <div className="mind-foot"><span>CORE · {view}</span><b>{roots.length} domains · {snapshot.projects.length} projects · {snapshot.researchTopics.length} research roots · {snapshot.plans.length} plans</b></div>
  </section>;
}
function Capabilities({ snapshot }: { snapshot: JarvisSnapshot }) { return <section className="space-panel panel"><div className="panel-kicker">CAPABILITY FABRIC</div><h1>Capabilities</h1><p className="space-subtitle">Where JARVIS discovers, organizes and explains what it can use without gaining authority.</p><div className="capability-grid">{snapshot.capabilities.map((cap) => <div className="capability-card" key={cap.id}><div><span className={`state-dot ${cap.state.toLowerCase()}`} /><b>{cap.name}</b><span>{cap.state}</span></div><p>{cap.detail}</p></div>)}</div><div className="expansion-rail"><span>SELF-BUILDING FABRIC</span><b>Models · Plugins · Integrations · Workers · Skills · Devices · Automations</b><p>JARVIS can eventually populate, test and explain this inventory as capability systems grow.</p></div></section>; }
function Self({ snapshot }: { snapshot: JarvisSnapshot }) { return <section className="space-panel panel"><div className="panel-kicker">SELF OBSERVATION</div><div className="self-head"><div><h1>Self</h1><p className="space-subtitle">Watch JARVIS think, delegate, communicate and protect system resources.</p></div><div className={`self-pressure pressure-${snapshot.resources.pressure.toLowerCase()}`}><span>{snapshot.resources.pressure}</span><b>{snapshot.resources.strategy.replace('_', ' ')}</b></div></div><div className="self-runtime"><div className="resource-meters">{[['CPU', snapshot.resources.cpuLoad], ['MEMORY', snapshot.resources.memoryLoad], ['GPU', snapshot.resources.gpuLoad]].map(([label, value]) => <div key={label}><span>{label}</span><b>{value}%</b><div className="resource-bar"><i style={{ width: `${value}%` }} /></div></div>)}</div><div className="delegation-state"><span className="surface-label">MODEL COORDINATION</span><strong>{snapshot.resources.activeModelTasks} ACTIVE TASK</strong><p>{snapshot.resources.concurrencyLimit === 1 ? 'Sequential model handoff is active.' : 'Limited parallel model work is available.'}</p></div></div><div className="self-activity"><div className="panel-heading"><span>JARVIS ACTIVITY</span><small>LIVE INTERNAL VIEW</small></div>{snapshot.selfActivity.map((item) => <div className="self-activity-row" key={item.id}><span className={`self-activity-icon self-${item.kind.toLowerCase()}`}><i /></span><div><b>{item.title}</b><p>{item.detail}</p></div><div className="self-model">{item.modelId ? snapshot.models.find((model) => model.id === item.modelId)?.name ?? item.modelId : 'JARVIS'}<small>{item.timestamp}</small></div></div>)}</div><div className="self-grid">{[['Architecture','Core authority remains backend-owned.'],['Mind','Internal context, memory and relationships are represented separately.'],['Learning','Learning signals remain distinct from truth and authority.'],['Models',`${snapshot.models.length} model roles are represented.`],['Capabilities',`${snapshot.capabilities.length} currently known capabilities.`],['Resource policy','JARVIS observes system pressure before increasing model concurrency.']].map(([title, detail]) => <div className="self-card" key={title}><span>{title}</span><p>{detail}</p></div>)}</div></section>; }

export default App;
