import { useEffect, useState } from 'react';
import { demoGateway } from './demoGateway';
import { Icon, type IconName } from './icons';
import type { ChatSurface, JarvisSnapshot, ProjectState, SelfActivityKind } from './contracts';

type Space = 'HOME' | 'CHAT' | 'PROJECTS' | 'MIND' | 'CAPABILITIES' | 'SELF';
const spaces: Space[] = ['HOME', 'CHAT', 'PROJECTS', 'MIND', 'CAPABILITIES', 'SELF'];
const icons: Record<Space, IconName> = { HOME: 'home', CHAT: 'chat', PROJECTS: 'projects', MIND: 'mind', CAPABILITIES: 'capabilities', SELF: 'self' };
const chatLabels: Record<ChatSurface, string> = { CONVERSATION: 'Conversation', WORKSPACE: 'Workspace', RESEARCH: 'Research', PLANNING: 'Planning' };
const selfLabels: Record<SelfActivityKind, string> = { THINKING: 'Thinking', DELEGATING: 'Delegating', COMMUNICATING: 'Communicating', WAITING: 'Waiting', RESOURCE_GUARD: 'Resource guard' };

export default function AppNext() {
  const [space, setSpace] = useState<Space>('HOME');
  const [collapsed, setCollapsed] = useState(false);
  const [snapshot, setSnapshot] = useState<JarvisSnapshot>(() => demoGateway.snapshotSync());
  const [surface, setSurface] = useState<ChatSurface>('CONVERSATION');
  const [composer, setComposer] = useState('');
  const [workspaceId, setWorkspaceId] = useState('jarvis');
  const [projectId, setProjectId] = useState('jarvis-interface');
  const [history, setHistory] = useState<Record<ChatSurface, string[]>>({ CONVERSATION: [], WORKSPACE: [], RESEARCH: [], PLANNING: [] });

  useEffect(() => demoGateway.subscribe('desktop', () => setSnapshot(demoGateway.snapshotSync())), []);

  const submit = async () => {
    const text = composer.trim();
    if (!text) return;
    setHistory((current) => ({ ...current, [surface]: [...current[surface], text] }));
    setComposer('');
    await demoGateway.submit({ text, sessionId: 'desktop', surface });
    setSnapshot(demoGateway.snapshotSync());
    setSpace('CHAT');
  };

  const controlProject = async (id: string, state: Extract<ProjectState, 'ACTIVE' | 'PAUSED'>) => {
    await demoGateway.submit({ text: `${state === 'PAUSED' ? 'Pause' : 'Resume'} project ${id}`, sessionId: 'desktop', surface: 'PROJECTS', projectId: id });
    setSnapshot(demoGateway.snapshotSync());
  };

  const selectDirectory = async () => {
    const picker = (window as Window & { showDirectoryPicker?: () => Promise<{ name: string }> }).showDirectoryPicker;
    if (!picker) return;
    const directory = await picker();
    await demoGateway.submit({ text: `Select workspace directory ${directory.name}`, sessionId: 'desktop', surface: 'WORKSPACE' });
    const next = demoGateway.snapshotSync();
    const chosen = next.workspaces.find((item) => item.name === directory.name);
    if (chosen) setWorkspaceId(chosen.id);
    setSnapshot(next);
  };

  return <div className={`shell ${collapsed ? 'nav-collapsed' : 'nav-expanded'}`}>
    <div className="ambient ambient-a" /><div className="ambient ambient-b" /><div className="ambient-core" aria-hidden="true"><span /></div>
    <aside className="sidebar" aria-label="JARVIS navigation">
      <div className="sidebar-brand"><button className="brand" onClick={() => setSpace('HOME')} aria-label="JARVIS Home"><span className="brand-mark">J</span><span className="brand-word">JARVIS</span></button><button className="sidebar-toggle" onClick={() => setCollapsed((v) => !v)} aria-label={collapsed ? 'Expand navigation' : 'Collapse navigation'}><Icon name="menu" /></button></div>
      <nav className="sidebar-nav">{spaces.map((item) => <button key={item} className={item === space ? 'nav-item active' : 'nav-item'} onClick={() => setSpace(item)} title={collapsed ? item : undefined}><Icon name={icons[item]} /><span>{item}</span></button>)}</nav>
      <div className="sidebar-foot"><span className="sidebar-resource-dot" /><div><b>RESOURCE GUARD</b><small>{snapshot.resources.strategy} · {snapshot.resources.pressure}</small></div></div>
    </aside>

    <header className="topbar"><div className="topbar-left"><span className="top-context">{space}</span><span className="top-divider" /><span className="top-focus">{space === 'SELF' ? 'Internal runtime' : space === 'MIND' ? 'Cognitive workspace' : 'JARVIS'}</span></div><div className="topbar-right"><span className="top-device">{snapshot.device.name}</span></div></header>

    <main className="layout">
      {space === 'HOME' && <Home snapshot={snapshot} navigate={setSpace} />}
      {space === 'CHAT' && <Chat surface={surface} setSurface={setSurface} history={history[surface]} composer={composer} setComposer={setComposer} submit={submit} snapshot={snapshot} workspaceId={workspaceId} setWorkspaceId={setWorkspaceId} selectDirectory={selectDirectory} projectId={projectId} setProjectId={setProjectId} />}
      {space === 'PROJECTS' && <Projects snapshot={snapshot} selectedId={projectId} setSelectedId={setProjectId} controlProject={controlProject} />}
      {space === 'MIND' && <Mind snapshot={snapshot} />}
      {space === 'CAPABILITIES' && <Capabilities snapshot={snapshot} />}
      {space === 'SELF' && <Self snapshot={snapshot} />}
    </main>
  </div>;
}

function Home({ snapshot, navigate }: { snapshot: JarvisSnapshot; navigate: (space: Space) => void }) {
  return <section className="home-grid">
    <div className="panel cockpit"><div className="panel-kicker">AWARENESS</div><div className="cockpit-body"><div><span className="signal-label">WHAT MATTERS NOW</span><strong>{snapshot.currentFocus}</strong><p>{snapshot.attentionReason}</p><div className="awareness-actions"><button className="primary-action" onClick={() => navigate('PROJECTS')}>Projects</button><button className="soft-action compact" onClick={() => navigate('MIND')}>Mind</button></div></div><div className="signal-ring"><span>{snapshot.projects.filter((p) => p.state === 'ACTIVE').length}</span><small>ACTIVE PROJECTS</small></div></div><div className="cockpit-footer"><span>{snapshot.attentionRequired ? 'Attention required' : 'System oriented'}</span><b>{snapshot.attentionRequired ? 'Review' : 'Clear'}</b></div></div>
    <div className={`panel attention ${snapshot.attentionRequired ? 'attention-hot' : ''}`}><div className="panel-kicker">ATTENTION</div><div className="attention-number">{snapshot.attentionRequired ? 'YES' : 'CLEAR'}</div><div className="attention-copy">{snapshot.attentionReason}</div><button className="text-action" onClick={() => navigate('PROJECTS')}>Review →</button></div>
    <div className="panel intelligence wide"><div className="panel-heading"><span>RECENT INTELLIGENCE</span><small>CONTEXT</small></div><div className="activity-list">{snapshot.activity.map((item) => <div className="activity-item" key={item.id}><span className="activity-dot" /><div><b>{item.title}</b><p>{item.detail}</p></div><time>{item.timestamp}</time></div>)}</div></div>
    <div className="panel work-overview"><div className="panel-heading"><span>PROJECTS</span><small>{snapshot.projects.length} TOTAL</small></div>{snapshot.projects.slice(0, 4).map((project) => <div className="project" key={project.id}><div><b>{project.name}</b><span>{project.state}</span></div>{typeof project.progress === 'number' && <div className="bar"><span style={{ width: `${project.progress}%` }} /></div>}</div>)}<button className="panel-action" onClick={() => navigate('PROJECTS')}>Open projects →</button></div>
    <div className="panel capability-overview"><div className="panel-heading"><span>SYSTEM FABRIC</span><small>OBSERVED</small></div><div className="cap-row"><span className="state-dot ready" /><b>Device</b><span>{snapshot.device.os}</span></div><div className="cap-row"><span className="state-dot connected" /><b>Models</b><span>{snapshot.models.length} REGISTERED</span></div><div className="cap-row"><span className="state-dot online" /><b>Capabilities</b><span>{snapshot.capabilities.length} KNOWN</span></div><button className="panel-action" onClick={() => navigate('CAPABILITIES')}>Open capabilities →</button></div>
    <div className="panel device-overview"><div className="panel-heading"><span>DEVICE</span><small>{snapshot.device.name}</small></div><div className="device-grid">{Object.entries({ CPU: snapshot.device.cpu, MEMORY: snapshot.device.memory, GPU: snapshot.device.gpu, STORAGE: snapshot.device.storage }).map(([label, value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</div></div>
    <div className="panel model-overview"><div className="panel-heading"><span>MODEL ASSIGNMENTS</span><small>ROLE / STATE</small></div>{snapshot.models.map((model) => <div className="model-row" key={model.id}><div><b>{model.name}</b><span>{model.role}</span></div><strong>{model.state}</strong></div>)}</div>
  </section>;
}

function Chat({ surface, setSurface, history, composer, setComposer, submit, snapshot, workspaceId, setWorkspaceId, selectDirectory, projectId, setProjectId }: { surface: ChatSurface; setSurface: (s: ChatSurface) => void; history: string[]; composer: string; setComposer: (v: string) => void; submit: () => Promise<void>; snapshot: JarvisSnapshot; workspaceId: string; setWorkspaceId: (id: string) => void; selectDirectory: () => Promise<void>; projectId: string; setProjectId: (id: string) => void }) {
  const activeWorkspace = snapshot.workspaces.find((w) => w.id === workspaceId) ?? snapshot.workspaces[0];
  const activeProject = snapshot.projects.find((p) => p.id === projectId) ?? snapshot.projects[0];
  const info: Record<ChatSurface, { kicker: string; description: string; placeholder: string; tag: string }> = {
    CONVERSATION: { kicker: 'GENERAL INTELLIGENCE', description: 'General conversation with its own browsable history.', placeholder: 'Talk to JARVIS...', tag: 'TALK' },
    WORKSPACE: { kicker: 'LITERAL WORKSPACE', description: 'A directory-rooted environment for inspect, generate, edit, code and verify.', placeholder: `Command JARVIS in ${activeWorkspace?.name ?? 'this workspace'}...`, tag: 'BUILD' },
    RESEARCH: { kicker: 'ENGINEERING THINK TANK', description: 'A place to gather evidence, brainstorm, challenge and think.', placeholder: 'Add a research direction, question, source or thought...', tag: 'THINK' },
    PLANNING: { kicker: 'PLANNING + AUTOMATION', description: 'A place to prepare work and automation for JARVIS to execute.', placeholder: 'Describe an outcome or automation...', tag: 'PLAN' },
  };
  const active = info[surface];
  const saved = snapshot.chatHistory.filter((item) => item.surface === surface);
  return <section className="chat-shell"><aside className="chat-sidebar panel"><div className="panel-kicker">{chatLabels[surface].toUpperCase()}</div><button className="chat-new">+ New {chatLabels[surface].toLowerCase()}</button>{(Object.keys(chatLabels) as ChatSurface[]).map((item) => <button key={item} className={item === surface ? 'chat-mode active' : 'chat-mode'} onClick={() => setSurface(item)}><span>{chatLabels[item]}</span><small>{info[item].tag}</small></button>)}
    <div className="chat-toolbox history-box"><span className="panel-kicker">{surface === 'RESEARCH' ? 'RESEARCH HISTORY' : surface === 'CONVERSATION' ? 'CONVERSATION HISTORY' : `${chatLabels[surface].toUpperCase()} HISTORY`}</span>{saved.map((entry) => <button className="history-item" key={entry.id}><b>{entry.title}</b><small>{entry.timestamp}</small><span>{entry.preview}</span></button>)}{history.length === 0 && <div className="history-empty">No local messages in this session.</div>}</div>
    {surface === 'WORKSPACE' && <div className="chat-toolbox"><span className="panel-kicker">WORKSPACE ROOT</span>{snapshot.workspaces.map((w) => <button className={`workspace-item ${w.id === workspaceId ? 'selected' : ''}`} key={w.id} onClick={() => setWorkspaceId(w.id)}><b>{w.name}</b><small>{w.path}</small></button>)}<button className="soft-action" onClick={() => void selectDirectory()}>+ Select directory</button><div className="workspace-project-link"><span>PROJECT</span><button onClick={() => setProjectId(activeProject.id)}>{activeProject.name}</button></div></div>}
    {surface === 'RESEARCH' && <div className="chat-toolbox"><span className="panel-kicker">TOPICS</span>{snapshot.researchTopics.map((topic) => <button className="research-topic" key={topic.id}><b>{topic.title}</b><small>{topic.state} · {topic.sourceCount} sources · {topic.thoughtCount} thoughts</small></button>)}</div>}
    {surface === 'PLANNING' && <div className="chat-toolbox"><span className="panel-kicker">PLANS</span>{snapshot.plans.map((plan) => <button className="plan-item" key={plan.id}><b>{plan.title}</b><small>{plan.state}{plan.automation ? ` · ${plan.automation}` : ''}</small></button>)}</div>}
  </aside><section className="panel chat-main"><div className="chat-header"><div><span className="panel-kicker">{active.kicker}</span><h1>{chatLabels[surface]}</h1><p>{active.description}</p></div><span className="chat-status"><i /> ready</span></div>{surface === 'CONVERSATION' && <div className="chat-history">{history.length === 0 ? <div className="chat-empty"><span className="empty-orb" /><h2>Talk to JARVIS.</h2><p>Conversation history stays here.</p></div> : history.map((message, index) => <div className="chat-message" key={`${message}-${index}`}><span>YOU</span><p>{message}</p></div>)}</div>}{surface === 'WORKSPACE' && <WorkspaceSurface workspace={activeWorkspace} />}{surface === 'RESEARCH' && <ResearchSurface snapshot={snapshot} />}{surface === 'PLANNING' && <PlanningSurface snapshot={snapshot} />}<div className="chat-composer"><textarea value={composer} onChange={(e) => setComposer(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); void submit(); } }} placeholder={active.placeholder} /><button onClick={() => void submit()}>↑</button></div></section></section>;
}

function WorkspaceSurface({ workspace }: { workspace?: JarvisSnapshot['workspaces'][number] }) { return <div className="special-surface"><div className="workspace-banner"><div><span className="surface-label">WORKSPACE ROOT</span><h2>{workspace?.name ?? 'No workspace selected'}</h2><p>{workspace?.path ?? 'Select a directory.'}</p></div><span className="surface-state">{workspace?.status ?? 'AVAILABLE'}</span></div><div className="workspace-grid">{[['INSPECT','Understand before changing'],['GENERATE','Build inside the root'],['EDIT','Modify existing work'],['VERIFY','Prove the result']].map(([label,title]) => <div className="surface-card" key={label}><span>{label}</span><b>{title}</b><p>Workspace operations remain rooted in this selected environment.</p></div>)}</div></div>; }
function ResearchSurface({ snapshot }: { snapshot: JarvisSnapshot }) { return <div className="special-surface"><div className="research-command"><div><span className="surface-label">THINK TANK</span><h2>Think with the material.</h2><p>Research is for engineering, brainstorming and deliberate thought.</p></div></div><div className="research-board">{snapshot.researchTopics.map((topic) => <article className="research-card" key={topic.id}><div className="research-card-top"><span>{topic.state}</span><button>THINK →</button></div><h3>{topic.title}</h3><p>{topic.detail}</p><div className="research-footer"><span>{topic.sourceCount} SOURCES · {topic.thoughtCount} THOUGHTS</span><b>{topic.lastThought ?? 'Awaiting deeper thought.'}</b></div></article>)}</div></div>; }
function PlanningSurface({ snapshot }: { snapshot: JarvisSnapshot }) { return <div className="special-surface"><div className="planning-command"><div><span className="surface-label">PLANNING + AUTOMATION</span><h2>Prepare JARVIS to execute.</h2><p>Plans can represent direct project work or recurring automation such as scraping and monitoring.</p></div></div><div className="plan-board">{snapshot.plans.map((plan) => <article className="plan-card" key={plan.id}><div className="plan-card-top"><span>{plan.state}</span><b>{plan.steps.length} STEPS</b></div><h3>{plan.title}</h3>{plan.automation && <div className="automation-label">AUTOMATION · {plan.automation}</div>}{plan.steps.map((step, index) => <div className={`plan-step ${plan.currentStep === index + 1 ? 'current' : ''}`} key={step}><span>{index + 1}</span>{step}</div>)}</article>)}</div></div>; }

function Projects({ snapshot, selectedId, setSelectedId, controlProject }: { snapshot: JarvisSnapshot; selectedId: string; setSelectedId: (id: string) => void; controlProject: (id: string, state: Extract<ProjectState, 'ACTIVE' | 'PAUSED'>) => Promise<void> }) { const selected = snapshot.projects.find((p) => p.id === selectedId) ?? snapshot.projects[0]; return <section className="space-panel panel"><div className="work-control-head"><div><div className="panel-kicker">PROJECT CONTROL</div><h1>Projects</h1><p className="space-subtitle">Editable work objects with progress, workspace, plans and user guidance.</p></div></div><div className="project-control-layout"><aside className="project-list">{snapshot.projects.map((project) => <button key={project.id} className={project.id === selected.id ? 'project-select active' : 'project-select'} onClick={() => setSelectedId(project.id)}><span>{project.state}</span><b>{project.name}</b><small>{project.progress ?? 0}% · {project.currentAction ?? 'No current action'}</small></button>)}</aside><div className="project-detail"><div className="work-runtime"><div><span className="surface-label">PROJECT STATE</span><strong>{selected.state}</strong><p>{selected.detail ?? 'Project context is being maintained.'}</p></div>{(selected.state === 'ACTIVE' || selected.state === 'PAUSED') && <button className={`control-toggle ${selected.state === 'PAUSED' ? 'paused' : ''}`} onClick={() => void controlProject(selected.id, selected.state === 'ACTIVE' ? 'PAUSED' : 'ACTIVE')}><span />{selected.state === 'PAUSED' ? 'RESUME' : 'PAUSE'}</button>}</div><div className="project-detail-grid"><div className="surface-card"><span>PROGRESS</span><b>{selected.progress ?? 0}%</b>{typeof selected.progress === 'number' && <div className="bar"><span style={{ width: `${selected.progress}%` }} /></div>}<p>{selected.currentAction ?? 'No active operation.'}</p></div><div className="surface-card"><span>WORKSPACE</span><b>{snapshot.workspaces.find((w) => w.id === selected.workspaceId)?.name ?? 'Not assigned'}</b><p>{snapshot.workspaces.find((w) => w.id === selected.workspaceId)?.path ?? 'Select in Workspace.'}</p></div><div className="surface-card"><span>FEEDBACK</span><b>{selected.state === 'PAUSED' ? 'OPEN' : 'READY'}</b><p>{selected.state === 'PAUSED' ? 'Add guidance before resuming.' : 'Pause to steer the next step.'}</p></div><div className="surface-card"><span>PLANS</span><b>{snapshot.plans.filter((plan) => plan.target === selected.name || plan.target === 'JARVIS UI').length}</b><p>Planning artifacts connected to this project.</p></div></div></div></div></section>; }

function Mind({ snapshot }: { snapshot: JarvisSnapshot }) { const [view, setView] = useState<'EXPLORER' | 'GRAPH' | 'THINKING'>('EXPLORER'); const roots = ['Personal','Skills','Preferences','Projects','Goals','Facts','Workflows','Relationships','Experiences','Knowledge','Plans','Learning']; return <section className="space-panel panel"><div className="panel-kicker">MIND CORE</div><div className="space-heading-row"><div><h1>Mind</h1><p className="space-subtitle">Internal world: memory, context, thinking, plans, learning and relationships.</p></div><div className="segmented"><button className={view === 'EXPLORER' ? 'active' : ''} onClick={() => setView('EXPLORER')}>Explorer</button><button className={view === 'GRAPH' ? 'active' : ''} onClick={() => setView('GRAPH')}>Graph</button><button className={view === 'THINKING' ? 'active' : ''} onClick={() => setView('THINKING')}>Thinking</button></div></div>{view === 'EXPLORER' && <div className="folder-grid">{roots.map((root) => <div className="folder" key={root}><span>◈</span><b>{root}</b><small>core system</small></div>)}</div>}{view === 'GRAPH' && <div className="relationship-map"><span className="node center">MIND CORE</span><span className="node n1">MEMORY</span><span className="node n2">THINKING</span><span className="node n3">PLANS</span><span className="node n4">LEARNING</span><span className="node n5">PROJECTS</span><span className="node n6">RELATIONSHIPS</span>{['c1','c2','c3','c4','c5','c6'].map((c) => <div className={`connection ${c}`} key={c} />)}</div>}{view === 'THINKING' && <div className="mind-thinking-grid"><div className="surface-card"><span>ACTIVE CONTEXT</span><b>{snapshot.currentFocus}</b><p>What JARVIS currently considers relevant.</p></div>{snapshot.researchTopics.map((topic) => <div className="surface-card" key={topic.id}><span>{topic.state}</span><b>{topic.title}</b><p>{topic.lastThought ?? 'Awaiting deeper thought.'}</p></div>)}</div>}<div className="mind-foot"><span>Explorer · Graph · Thinking</span><b>{snapshot.projects.length} projects · {snapshot.researchTopics.length} research roots · {snapshot.plans.length} plans</b></div></section>; }

function Capabilities({ snapshot }: { snapshot: JarvisSnapshot }) { return <section className="space-panel panel"><div className="panel-kicker">CAPABILITY FABRIC</div><h1>Capabilities</h1><p className="space-subtitle">What JARVIS can use: skills, tools, models, integrations, workers and automations.</p><div className="capability-grid">{snapshot.capabilities.map((cap) => <div className="capability-card" key={cap.id}><div><span className={`state-dot ${cap.state.toLowerCase()}`} /><b>{cap.name}</b><span>{cap.state}</span></div><p>{cap.detail}</p></div>)}</div><div className="expansion-rail"><span>SELF-BUILDING FABRIC</span><b>Models · Plugins · Integrations · Workers · Skills · Devices · Automations</b><p>This inventory is designed to grow as JARVIS discovers and integrates useful capabilities.</p></div></section>; }

function Self({ snapshot }: { snapshot: JarvisSnapshot }) { const [filter, setFilter] = useState<'ALL' | SelfActivityKind>('ALL'); const activity = snapshot.selfActivity.filter((item) => filter === 'ALL' || item.kind === filter); const current = activity[0] ?? snapshot.selfActivity[0]; const filterLabel = (item: 'ALL' | SelfActivityKind) => item === 'ALL' ? 'All' : selfLabels[item]; return <section className="space-panel panel"><div className="panel-kicker">SELF OBSERVATION</div><div className="self-head"><div><h1>Self</h1><p className="space-subtitle">Where JARVIS shows what it is doing, model involvement and resource-aware behavior.</p></div><span className={`surface-state pressure-state-${snapshot.resources.pressure.toLowerCase()}`}>{snapshot.resources.pressure}</span></div><div className="self-runtime"><div className="self-runtime-copy"><span className="surface-label">CURRENT ACTIVITY</span><strong>{selfLabels[current.kind]}</strong><p>{current.detail}</p><div className="runtime-bar"><span style={{ width: `${Math.min(100, snapshot.resources.activeModelTasks / Math.max(1, snapshot.resources.concurrencyLimit) * 100)}%` }} /></div><small>{snapshot.resources.activeModelTasks} active model task · limit {snapshot.resources.concurrencyLimit}</small></div><div className="self-runtime-stats"><div><span>CPU</span><b>{snapshot.resources.cpuLoad}%</b></div><div><span>MEMORY</span><b>{snapshot.resources.memoryLoad}%</b></div><div><span>GPU</span><b>{snapshot.resources.gpuLoad}%</b></div><div><span>STRATEGY</span><b>{snapshot.resources.strategy}</b></div></div></div><div className="self-filters">{(['ALL','THINKING','DELEGATING','COMMUNICATING','WAITING','RESOURCE_GUARD'] as const).map((item) => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{filterLabel(item)}</button>)}</div><div className="self-activity-list">{activity.map((item) => <div className="self-activity" key={item.id}><div className={`self-icon kind-${item.kind.toLowerCase()}`}><Icon name={item.kind === 'DELEGATING' ? 'capabilities' : item.kind === 'COMMUNICATING' ? 'chat' : item.kind === 'RESOURCE_GUARD' ? 'self' : 'mind'} size={16} /></div><div><div className="self-activity-heading"><b>{item.title}</b><span>{item.timestamp}</span></div><p>{item.detail}</p>{item.modelId && <small>MODEL · {snapshot.models.find((m) => m.id === item.modelId)?.name ?? item.modelId}</small>}</div></div>)}</div><div className="self-scheduling"><div><span className="surface-label">MODEL SCHEDULING</span><b>One model at a time by default.</b><p>Concurrency becomes an option only when actual resource pressure and task boundaries permit it. Under strain, JARVIS should reduce load or defer non-urgent work.</p></div><div className="model-queue">{snapshot.models.map((model) => <div className="queue-row" key={model.id}><span>{model.state}</span><b>{model.name}</b><small>{model.role}</small></div>)}</div></div></section>; }
