from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class PlanStatus(str, Enum):
    """
    Lifecycle state of an execution plan.
    """

    DRAFT = "DRAFT"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class StepStatus(str, Enum):
    """
    Lifecycle state of an individual plan step.
    """

    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


@dataclass(frozen=True)
class PlanStep:
    """
    One atomic unit of work in an ExecutionPlan.
    """

    step_id: str

    description: str

    action: str

    order: int

    depends_on: tuple[str, ...] = ()

    status: StepStatus = StepStatus.PENDING

    requires_confirmation: bool = False

    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    def __post_init__(self):

        if not isinstance(
            self.step_id,
            str,
        ):
            raise TypeError(
                "step_id must be a string."
            )

        if not self.step_id.strip():
            raise ValueError(
                "step_id cannot be empty."
            )

        if not isinstance(
            self.description,
            str,
        ):
            raise TypeError(
                "description must be a string."
            )

        if not self.description.strip():
            raise ValueError(
                "description cannot be empty."
            )

        if not isinstance(
            self.action,
            str,
        ):
            raise TypeError(
                "action must be a string."
            )

        if not self.action.strip():
            raise ValueError(
                "action cannot be empty."
            )

        if not isinstance(
            self.order,
            int,
        ):
            raise TypeError(
                "order must be an integer."
            )

        if self.order < 0:
            raise ValueError(
                "order cannot be negative."
            )

        if not isinstance(
            self.depends_on,
            tuple,
        ):
            raise TypeError(
                "depends_on must be a tuple."
            )


@dataclass(frozen=True)
class ExecutionPlan:
    """
    Structured plan generated by JARVIS for a task.

    The plan describes intended work.
    It does not execute anything.
    """

    plan_id: str

    task_description: str

    steps: tuple[PlanStep, ...]

    status: PlanStatus = PlanStatus.DRAFT

    metadata: dict[str, Any] = field(
        default_factory=dict
    )

    def __post_init__(self):

        if not isinstance(
            self.plan_id,
            str,
        ):
            raise TypeError(
                "plan_id must be a string."
            )

        if not self.plan_id.strip():
            raise ValueError(
                "plan_id cannot be empty."
            )

        if not isinstance(
            self.task_description,
            str,
        ):
            raise TypeError(
                "task_description must be a string."
            )

        if not self.task_description.strip():
            raise ValueError(
                "task_description cannot be empty."
            )

        if not isinstance(
            self.steps,
            tuple,
        ):
            raise TypeError(
                "steps must be a tuple."
            )

        seen = set()

        for step in self.steps:

            if not isinstance(
                step,
                PlanStep,
            ):
                raise TypeError(
                    "All plan steps must be PlanStep instances."
                )

            if step.step_id in seen:
                raise ValueError(
                    f"Duplicate step_id: {step.step_id}"
                )

            seen.add(
                step.step_id
            )

        step_ids = {
            step.step_id
            for step in self.steps
        }

        for step in self.steps:

            for dependency in step.depends_on:

                if dependency not in step_ids:
                    raise ValueError(
                        f"Step '{step.step_id}' "
                        f"depends on unknown step "
                        f"'{dependency}'."
                    )